repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
  - repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
        pass_filenames: true
        exclude: baselayer|node_modules|static
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 6ba454799f284b13ccd53ca2adaf4848da6d3509 # v0.0.240
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.3.0" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        pass_filenames: true
  - repo: local
    hooks:
      - id: ESLint
        name: ESLint
        entry: npx eslint -c .eslintrc.yaml --fix
        language: system
        files: \.[j]sx?$
        types: [file]
