repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
  - repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
        pass_filenames: true
        exclude: baselayer|node_modules|static
  - repo: https://github.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        pass_filenames: true
        exclude: baselayer|node_modules|static|__init__.py
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.3.0" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        pass_filenames: true
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 5d73b3501b5fd211a62693736b2ab83816855ebe # v8.33.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.33.0
          - "@babel/eslint-parser@7.19.1"
          - eslint-config-airbnb@18.2.0
          - eslint-config-prettier@8.6.0
          - eslint-plugin-import@2.22.1
          - eslint-plugin-jsx-a11y@6.3.1
          - eslint-plugin-react@7.22.0
          - eslint-plugin-react-hooks@4.2.0
        files: \.[j]sx?$
        types: [file]
